name: Java CI with Maven

on:
  push:
    branches:
      - main  # Adjust this branch name to match your main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8  # Change this to your desired Java version
          distribution: 'zulu'

      - name: Git Version
        uses: codacy/git-version@2.5.4
        with:
          tool-version: 2.24.1
          
      # - name: Add to cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cache

      # - name: Build with Maven
      #   run: |
      #     mvn clean install
      
      # - name: Test cache
      #   run : |
      #     cd ~/.m2
      #     ls -R
      # - name: Build with Maven
      #   run: |
      #     mvn clean package
      
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-java-project-artifact
      #     path: target/*.jar 
